// GENERATED by scripts/measure-sprite-icons.py — do not edit by hand.
//
// Per-Sprite scale factors that make catalog icons render at a uniform
// visual size. Every source icon is a 512x512 square, but the artwork
// inside fills a different share of that canvas. Size is judged the way the
// eye does, from two measures at once: visual mass (the square root of the
// opaque pixel area) and the art's height. Mass alone left short, wide
// sprites like 8-Bit reading small next to tall ones; height alone
// (tried twice) shrank narrow, tall ones. Each Sprite's size is the
// geometric mean of the two, and every factor scales it to one common
// target. The target is the largest that still keeps every sprite's longest
// side within 94% of its box, so factors can now go above 1 (small art is
// scaled UP to match) and nothing touches an edge. Measured 2026-09-26 in
// the browser on fortnite.gg's own origin (the icons are hotlink-protected
// and unreadable elsewhere).
//
// Unknown ids fall back to 1 — a new Sprite renders unscaled rather than
// wrong, until this is regenerated.
const ICON_SCALE: Record<string, number> = {
  "klombo-sprite": 0.946,
  "birthday-sprite": 0.9672,
  "mega-man-sprite": 0.9963,
  "morgana-sprite": 1.0003,
  "pond-sprite": 1.0033,
  "crown-sprite": 1.01,
  "crash-bandicoot-sprite": 1.0168,
  "overshield-sprite": 1.0188,
  "tails-sprite": 1.0224,
  "jackrabbit-sprite": 1.024,
  "shadow-sprite": 1.0356,
  "sonic-sprite": 1.043,
  "adventure-sprite": 1.0453,
  "storm-scout-sprite": 1.0699,
  "blinky-sprite": 1.0702,
  "killswitch-sprite": 1.0968,
  "bush-sprite": 1.1064,
  "x-ray-sprite": 1.1158,
  "8-bit-sprite": 1.1245,
  "onigiri-sprite": 1.1325,
  "jonesy-sprite": 1.145,
};

/**
 * Variant ids are the base id with a prefix ("gold-jonesy-sprite",
 * "loot-hacker-jonesy-sprite"). Every variant is a recolour of its family's
 * base art — same pose, same silhouette — so it takes the base's scale. Without
 * this, every variant fell back to 1 and rendered unscaled.
 */
const VARIANT_PREFIXES = ["gold-", "cheat-master-", "cheatmaster-", "loot-hacker-", "bounty-hunter-"];

/** Variants whose ids use the art's internal name rather than the family's. */
const BASE_ALIAS: Record<string, string> = {
  "bushranger-sprite": "bush-sprite",
  "body-slam-sprite": "crash-bandicoot-sprite",
};

/** 1 for anything unmeasured, so an unknown Sprite renders unscaled rather than wrong. */
export function spriteIconScale(id: string): number {
  if (id in ICON_SCALE) return ICON_SCALE[id];
  const prefix = VARIANT_PREFIXES.find((p) => id.startsWith(p));
  if (!prefix) return 1;
  const base = id.slice(prefix.length);
  return ICON_SCALE[BASE_ALIAS[base] ?? base] ?? 1;
}

/**
 * How far each Sprite's art sits off-centre in its 512px canvas, as the shift
 * (fraction of the canvas, x then y) that puts the art's opaque bounding box
 * dead centre. Most are drawn 5-10px left of centre and 10-20px low, so
 * without this they sat visibly off in their tiles. Measured 2026-09-27 on
 * fortnite.gg's own origin (alpha > 8). Every variant matched its base
 * Sprite's box to within 1px, so variants take the base's value, the same
 * way they take its scale.
 */
const ICON_OFFSET: Record<string, readonly [number, number]> = {
  "jonesy-sprite": [0.0195, -0.0332],
  "adventure-sprite": [0.0244, -0.0137],
  "bush-sprite": [-0.0049, 0.0088],
  "sonic-sprite": [-0.0049, -0.0059],
  "tails-sprite": [0.0059, -0.0068],
  "shadow-sprite": [-0.0244, -0.0107],
  "8-bit-sprite": [0.0264, -0.0254],
  "jackrabbit-sprite": [0.0215, -0.0059],
  "crown-sprite": [0.0137, -0.0107],
  "killswitch-sprite": [0.0186, -0.0469],
  "klombo-sprite": [-0.0156, 0.0020],
  "mega-man-sprite": [-0.0166, 0.0029],
  "overshield-sprite": [0.0273, -0.0010],
  "x-ray-sprite": [0.0137, -0.0195],
  "onigiri-sprite": [0.0244, -0.0225],
  "storm-scout-sprite": [-0.0410, -0.0098],
  "blinky-sprite": [0.0029, -0.0166],
  "birthday-sprite": [-0.0264, 0.0186],
  "crash-bandicoot-sprite": [0.0020, 0.0137],
  "pond-sprite": [0.0049, -0.0029],
  "morgana-sprite": [-0.0029, 0.0098],
};

function baseIdOf(id: string): string {
  const prefix = VARIANT_PREFIXES.find((p) => id.startsWith(p));
  const base = prefix ? id.slice(prefix.length) : id;
  return BASE_ALIAS[base] ?? base;
}

/**
 * The transform that sizes a Sprite's art to the shared visual size AND
 * centres it in its box. The offset is scaled with the art, since the shift
 * applies after scaling about the centre; translate percentages are of the
 * image's own box, which is the tile.
 */
export function spriteIconTransform(id: string): string {
  const scale = spriteIconScale(id);
  const [dx, dy] = ICON_OFFSET[baseIdOf(id)] ?? [0, 0];
  return `translate(${(dx * scale * 100).toFixed(2)}%, ${(dy * scale * 100).toFixed(2)}%) scale(${scale})`;
}
