// GENERATED by scripts/build-sprite-icon-metrics.py — do not edit by hand.
//
// Per-Sprite scale and offset that render every catalog icon at one
// visual size, centred in its box. Every source icon is a 512x512 square
// with the art drawn at a different size and position inside it. Size is
// judged from visual mass and the art's core box (its 3%-97% alpha span,
// so thin candles, ears and antennae don't count); the centre is halfway
// between that core box's centre and the alpha centroid. The shared size
// is kept for all; a Sprite whose thin tip would run past 96% of its box
// slides away from that edge, or shrinks by the least that fits.
// Measured 2026-09-28 in the browser on fortnite.gg's own origin (the
// icons are hotlink-protected elsewhere): scripts/data/sprite-icon-measurements.json.
//
// Unknown ids fall back to 1 and no offset — a new Sprite renders unscaled
// rather than wrong, until this is regenerated.
const ICON_SCALE: Record<string, number> = {
  "klombo-sprite": 0.9144,
  "mega-man-sprite": 0.9832,
  "birthday-sprite": 1.0048,
  "morgana-sprite": 1.0074,
  "blinky-sprite": 1.0257,
  "tails-sprite": 1.0276,
  "adventure-sprite": 1.0281,
  "overshield-sprite": 1.0302,
  "shadow-sprite": 1.0353,
  "sonic-sprite": 1.0415,
  "storm-scout-sprite": 1.0451,
  "crash-bandicoot-sprite": 1.0458,
  "jackrabbit-sprite": 1.0459,
  "pond-sprite": 1.0474,
  "crown-sprite": 1.0617,
  "killswitch-sprite": 1.0716,
  "x-ray-sprite": 1.0822,
  "bush-sprite": 1.0929,
  "jonesy-sprite": 1.0982,
  "onigiri-sprite": 1.1018,
  "8-bit-sprite": 1.1039,
};

/**
 * Variant ids are the base id with a prefix ("gold-jonesy-sprite",
 * "loot-hacker-jonesy-sprite"). Every variant is a recolour of its family's
 * base art — measured to within ~2px of the same box — so it takes the base's
 * scale and offset.
 */
const VARIANT_PREFIXES = ["gold-",  "cheat-master-",  "cheatmaster-",  "loot-hacker-",  "bounty-hunter-"];

/** Variants whose ids use the art's internal name rather than the family's. */
const BASE_ALIAS: Record<string, string> = {
  "bushranger-sprite": "bush-sprite",
  "body-slam-sprite": "crash-bandicoot-sprite",
};

function baseIdOf(id: string): string {
  const prefix = VARIANT_PREFIXES.find((p) => id.startsWith(p));
  const base = prefix ? id.slice(prefix.length) : id;
  return BASE_ALIAS[base] ?? base;
}

/** 1 for anything unmeasured, so an unknown Sprite renders unscaled rather than wrong. */
export function spriteIconScale(id: string): number {
  return ICON_SCALE[baseIdOf(id)] ?? 1;
}

/**
 * The shift (fraction of the canvas, x then y) that puts each Sprite's
 * visual centre at the box's centre.
 */
const ICON_OFFSET: Record<string, readonly [number, number]> = {
  "jonesy-sprite": [0.0144, -0.0169],
  "adventure-sprite": [0.0172, 0.0025],
  "bush-sprite": [0.0040, 0.0215],
  "sonic-sprite": [0.0092, 0.0013],
  "tails-sprite": [0.0024, 0.0030],
  "shadow-sprite": [-0.0014, -0.0023],
  "8-bit-sprite": [0.0144, -0.0010],
  "jackrabbit-sprite": [0.0126, -0.0059],
  "crown-sprite": [0.0159, -0.0185],
  "killswitch-sprite": [0.0046, -0.0241],
  "klombo-sprite": [-0.0019, 0.0056],
  "mega-man-sprite": [-0.0035, 0.0245],
  "overshield-sprite": [0.0083, 0.0077],
  "x-ray-sprite": [0.0120, -0.0038],
  "onigiri-sprite": [0.0204, -0.0137],
  "storm-scout-sprite": [-0.0174, 0.0002],
  "blinky-sprite": [0.0040, -0.0092],
  "birthday-sprite": [0.0087, -0.0031],
  "crash-bandicoot-sprite": [0.0142, 0.0137],
  "pond-sprite": [0.0187, -0.0025],
  "morgana-sprite": [-0.0058, 0.0096],
};

/**
 * The transform that sizes a Sprite's art to the shared visual size AND
 * centres it in its box. The offset is scaled with the art, since the shift
 * applies after scaling about the centre; translate percentages are of the
 * image's own box, which is the tile.
 */
export function spriteIconTransform(id: string): string {
  const scale = spriteIconScale(id);
  const [dx, dy] = ICON_OFFSET[baseIdOf(id)] ?? [0, 0];
  return `translate(${(dx * scale * 100).toFixed(2)}%, ${(dy * scale * 100).toFixed(2)}%) scale(${scale})`;
}
