/**
 * Ability descriptions shown in the Sprite detail panel, keyed by family.
 *
 * Authored copy that replaces the scraped catalog text. It lives in code rather
 * than in public/data/sprites.json on purpose: that file is regenerated by the
 * daily catalog refresh, which would overwrite edits made there. Every variant
 * of a family (Base, Gold, Cheat Master, Loot Hacker) shares its family's
 * ability. A family missing here falls back to the catalog's own text.
 */
export const SPRITE_ABILITIES: Record<string, string> = {
  Bush: "Grants a bush on you after a duration; at max level you also gain a bush on elimination. The wait between bushes shortens with each level up.",
  Adventure: "Upgrades a random item in your inventory with each level up.",
  "8-Bit": "Puts an 8-Bit Shotgun in your first chest and grants a score multiplier for it.",
  Jonesy: "Recovers some health or shields shortly after taking damage. The amount healed grows with each level up.",
  "Storm Scout":
    "Applies Overdrive after you take enough storm damage, needing less damage with each level up. At max level it reveals future Storm circles.",
  "Mega Man": "Reduces friction while sliding or swimming, so you slide farther with each level up.",
  Overshield: "Grants an Overshield, growing with each level up.",
  Onigiri: "Applies Overdrive after you eat or drink a consumable, lasting longer with each level up.",
  Sonic: "Gotta go fast — sprint faster with each level up.",
  Tails: "Double jump to hover in mid-air with Tails' help. Hover speed grows with each level up.",
  Shadow:
    "Automatically reloads unequipped weapons over time, faster with each level up. At max level it reloads your equipped weapon too.",
  Jackrabbit: "Grants a second jump in mid-air. The cooldown between jumps shortens with each level up.",
  "X-Ray": "Periodically marks enemies in an area around you — the detection radius grows with each level up.",
  Killswitch: "Aim while in mid-air to slow down and gain improved accuracy. Accuracy grows with each level up.",
  Crown: "Levels up only by winning matches — faster with Crown Wins. Mastering it unlocks new variants.",
  Klombo: "Grants random items at each level and levels up only by consuming items. Item quality improves with each level up.",
};
