import type { SpriteCatalog } from "./types";

/**
 * Single point of access for Sprite catalog data. Everything else in the
 * app (the catalog context, selector, map markers) calls `loadSpriteCatalog()`
 * and doesn't know or care where the data physically comes from.
 *
 * TODAY: reads the static, pre-built public/data/sprites.json (generated by
 * scripts/build-sprite-catalog.mjs from the Fortnite Fandom wiki — see that
 * file's header comment for the full pipeline).
 *
 * LATER: to move to a live API (e.g. api-fortnite.com) or a database-backed
 * updater, change only the body of this function — fetch from the new
 * source, normalize into `SpriteCatalog`, return it. No caller changes.
 */
export async function loadSpriteCatalog(): Promise<SpriteCatalog> {
  const res = await fetch("/data/sprites.json");
  if (!res.ok) {
    throw new Error(`Failed to load /data/sprites.json: ${res.status}`);
  }
  return res.json();
}
