#!/usr/bin/env python3
"""
Builds lib/sprite-icon-metrics.ts from scripts/data/sprite-icon-measurements.json.

The icons can't be measured from here (fortnite.gg hotlink-protects them), so
the measuring happens in a browser on fortnite.gg's own sprites page, where
they're same-origin: each icon is drawn to a canvas and its alpha read back.
See the JSON's _comment for the fields. This script only does the maths.

For every icon, two numbers:

  SIZE. How big the art reads, as the eye judges it: the geometric mean of its
  visual mass (sqrt of the opaque share) and its core box (sqrt of core width
  x core height). The core box is the 3%-97% span of the alpha mass, so thin
  protrusions — Birthday's candles, ears, antennae — don't inflate a Sprite's
  size and shrink its body. Every icon is scaled to one shared target size
  (TARGET), and any whose full art — protrusions included — would then run
  past 96% of its box slides or, failing that, shrinks just enough to fit.

  CENTRE. Where the art's visual centre sits: halfway between its core box's
  centre and its alpha centroid. The bounding box alone let a candle or an
  ear drag a Sprite off-centre; the centroid alone over-weights a heavy base.
  The offset moves that point to the box's centre.

Variants are measured individually, but every one matched its base Sprite to
within ~2px, so they share the base's numbers.

Usage: python3 scripts/build-sprite-icon-metrics.py
"""
import json
import math
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "scripts" / "data" / "sprite-icon-measurements.json"
OUT = ROOT / "lib" / "sprite-icon-metrics.ts"

MARGIN = 0.02  # each side: every icon's full art stays within 96% of its box
# The shared visual size, as a fraction of the box: the mean size the catalog
# drew its Sprites at before this pass (2026-09-27), kept so evening them out
# doesn't shrink or grow the catalog as a whole.
TARGET = 0.5976

VARIANT_PREFIXES = ["gold-", "cheat-master-", "cheatmaster-", "loot-hacker-", "bounty-hunter-"]


def visual_size(m):
    _, l, t, r, b, cl, ct, cr, cb, mx, my, area = m
    return math.sqrt(math.sqrt(area) * math.sqrt((cr - cl) * (cb - ct)))


def visual_centre(m):
    _, l, t, r, b, cl, ct, cr, cb, mx, my, area = m
    return (0.5 * (cl + cr) / 2 + 0.5 * mx, 0.5 * (ct + cb) / 2 + 0.5 * my)


def main():
    icons = json.loads(DATA.read_text())["icons"]
    bases = {k: v for k, v in icons.items() if not any(k.startswith(p) for p in VARIANT_PREFIXES)}

    offsets = {}
    for k, m in bases.items():
        cx, cy = visual_centre(m)
        offsets[k] = (0.5 - cx, 0.5 - cy)

    # One shared size for everyone: the size the catalog has always drawn them
    # at (the mean of the previous generation), so this pass evens them out
    # without shrinking the whole catalog.
    target = TARGET

    scales = {k: target / visual_size(m) for k, m in bases.items()}

    # A few Sprites have a thin tip (Jackrabbit's ears, Crash's hair, Crown's
    # crown, Birthday's candles) that would poke past the box's top once the
    # body is centred. Those slide the other way just far enough to clear it,
    # as long as the far side has the room; only if both sides are tight do
    # they shrink, by the least that fits. A rendered point p lands at
    # 0.5 + (p - 0.5 + d) * s.
    for k, m in bases.items():
        _, l, t, r, b = m[:5]
        for axis, lo, hi in ((0, l, r), (1, t, b)):
            d = list(offsets[k])
            sc = scales[k]
            near = 0.5 + (lo - 0.5 + d[axis]) * sc  # rendered low edge
            far = 1 - (0.5 + (hi - 0.5 + d[axis]) * sc)  # room at high edge
            if near >= MARGIN and far >= MARGIN:
                continue
            if near + far >= 2 * MARGIN:
                # Slide: even out the two sides, but never past MARGIN.
                shift = (MARGIN - near) if near < MARGIN else -(MARGIN - far)
                d[axis] += shift / sc
            else:
                # Shrink so the art spans exactly the box less both margins,
                # centred on that axis.
                sc = sc * (1 - 2 * MARGIN) / ((hi - lo) * sc)
                d[axis] = 0.5 - (lo + hi) / 2
                scales[k] = sc
            offsets[k] = (d[0], d[1])

    lines = [
        "// GENERATED by scripts/build-sprite-icon-metrics.py — do not edit by hand.",
        "//",
        "// Per-Sprite scale and offset that render every catalog icon at one",
        "// visual size, centred in its box. Every source icon is a 512x512 square",
        "// with the art drawn at a different size and position inside it. Size is",
        "// judged from visual mass and the art's core box (its 3%-97% alpha span,",
        "// so thin candles, ears and antennae don't count); the centre is halfway",
        "// between that core box's centre and the alpha centroid. The shared size",
        "// is kept for all; a Sprite whose thin tip would run past 96% of its box",
        "// slides away from that edge, or shrinks by the least that fits.",
        "// Measured 2026-09-28 in the browser on fortnite.gg's own origin (the",
        "// icons are hotlink-protected elsewhere): scripts/data/sprite-icon-measurements.json.",
        "//",
        "// Unknown ids fall back to 1 and no offset — a new Sprite renders unscaled",
        "// rather than wrong, until this is regenerated.",
        "const ICON_SCALE: Record<string, number> = {",
    ]
    for k, s in sorted(scales.items(), key=lambda kv: kv[1]):
        lines.append(f'  "{k}": {s:.4f},')
    lines += [
        "};",
        "",
        "/**",
        " * Variant ids are the base id with a prefix (\"gold-jonesy-sprite\",",
        " * \"loot-hacker-jonesy-sprite\"). Every variant is a recolour of its family's",
        " * base art — measured to within ~2px of the same box — so it takes the base's",
        " * scale and offset.",
        " */",
        "const VARIANT_PREFIXES = " + json.dumps(VARIANT_PREFIXES).replace(",", ", ") + ";",
        "",
        "/** Variants whose ids use the art's internal name rather than the family's. */",
        "const BASE_ALIAS: Record<string, string> = {",
        '  "bushranger-sprite": "bush-sprite",',
        '  "body-slam-sprite": "crash-bandicoot-sprite",',
        "};",
        "",
        "function baseIdOf(id: string): string {",
        "  const prefix = VARIANT_PREFIXES.find((p) => id.startsWith(p));",
        "  const base = prefix ? id.slice(prefix.length) : id;",
        "  return BASE_ALIAS[base] ?? base;",
        "}",
        "",
        "/** 1 for anything unmeasured, so an unknown Sprite renders unscaled rather than wrong. */",
        "export function spriteIconScale(id: string): number {",
        "  return ICON_SCALE[baseIdOf(id)] ?? 1;",
        "}",
        "",
        "/**",
        " * The shift (fraction of the canvas, x then y) that puts each Sprite's",
        " * visual centre at the box's centre.",
        " */",
        "const ICON_OFFSET: Record<string, readonly [number, number]> = {",
    ]
    for k in scales:
        dx, dy = offsets[k]
        lines.append(f'  "{k}": [{dx:.4f}, {dy:.4f}],')
    lines += [
        "};",
        "",
        "/**",
        " * The transform that sizes a Sprite's art to the shared visual size AND",
        " * centres it in its box. The offset is scaled with the art, since the shift",
        " * applies after scaling about the centre; translate percentages are of the",
        " * image's own box, which is the tile.",
        " */",
        "export function spriteIconTransform(id: string): string {",
        "  const scale = spriteIconScale(id);",
        "  const [dx, dy] = ICON_OFFSET[baseIdOf(id)] ?? [0, 0];",
        "  return `translate(${(dx * scale * 100).toFixed(2)}%, ${(dy * scale * 100).toFixed(2)}%) scale(${scale})`;",
        "}",
        "",
    ]
    OUT.write_text("\n".join(lines))

    # The audit: every family's rendered size and centre, which should now all
    # read 100% and (0, 0).
    print(f"shared target size {target:.4f}")
    for k, m in sorted(bases.items(), key=lambda kv: scales[kv[0]]):
        s = scales[k]
        dx, dy = offsets[k]
        cx, cy = visual_centre(m)
        rx, ry = 0.5 + (cx - 0.5 + dx) * s, 0.5 + (cy - 0.5 + dy) * s
        l, t, r, b = m[1:5]
        edge = min(0.5 + (l - 0.5 + dx) * s, 0.5 + (t - 0.5 + dy) * s, 1 - (0.5 + (r - 0.5 + dx) * s), 1 - (0.5 + (b - 0.5 + dy) * s))
        print(f"  {k:26s} scale {s:.3f}  size {visual_size(m) * s / target * 100:5.1f}%  centre ({(rx - .5) * 100:+.1f}%, {(ry - .5) * 100:+.1f}%)  nearest edge {edge * 100:.1f}%")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(scales)} families)")


if __name__ == "__main__":
    main()
