#!/usr/bin/env python3
"""
Measures how much of each Sprite icon's 512x512 canvas the artwork actually
fills, and writes lib/sprite-icon-metrics.ts.

Why this exists: every icon is the same 512x512 square, so an <img> box of a
fixed size renders them all at identical *box* dimensions — but the character
inside each canvas is drawn at a different scale (measured range: 71%-92% of
the canvas height). That makes the sprites look inconsistently sized in the
catalog headings even though their containers match. There's no CSS or
runtime fix: the icons are served without CORS headers, so the browser can't
read their pixels to measure them. Hence a build step.

Requires Pillow (`pip install Pillow`). Dev-only — never runs in the app.

Usage: python3 scripts/measure-sprite-icons.py
"""
import io
import json
import pathlib
import subprocess
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install Pillow")

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOG = ROOT / "public" / "data" / "sprites.json"
OUT = ROOT / "lib" / "sprite-icon-metrics.ts"

# fortnite.gg's CDN 403s a default user-agent. These are the same public,
# unprotected static assets the app already loads in the browser; we identify
# as a normal browser rather than bypassing any access control.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120 Safari/537.36"
)


def fetch(url: str) -> bytes:
    return subprocess.run(
        ["curl", "-sL", "-A", UA, url], check=True, capture_output=True
    ).stdout


def main() -> None:
    catalog = json.loads(CATALOG.read_text())
    sprites = catalog["sprites"] if isinstance(catalog, dict) else catalog
    bases = [
        s
        for s in sprites
        if s.get("variant") is None and s.get("currentlyLive") and s.get("icon")
    ]

    measured = {}
    for s in bases:
        img = Image.open(io.BytesIO(fetch(s["icon"]))).convert("RGBA")
        bbox = img.getbbox()  # bounds of non-transparent pixels
        if not bbox:
            continue
        content_h = bbox[3] - bbox[1]
        measured[s["id"]] = content_h / img.size[1]
        print(f"  {s['family']:16s} fills {measured[s['id']]* 100:5.1f}% of canvas height")

    if not measured:
        sys.exit("no icons measured")

    # Normalize DOWN to the least-filled icon so every sprite lands on the same
    # rendered height and none overflows its box (scaling up would spill into
    # neighboring rows).
    target = min(measured.values())
    scales = {sid: round(target / fill, 4) for sid, fill in measured.items()}

    lines = [
        "// GENERATED by scripts/measure-sprite-icons.py — do not edit by hand.",
        "//",
        "// Per-Sprite scale factors that make catalog icons render at a uniform",
        "// visual size. Every source icon is a 512x512 square, but the artwork",
        "// inside fills a different share of that canvas, so identical <img>",
        "// boxes still produce visibly different sprite sizes. Each factor below",
        "// is measured from the real icon's non-transparent bounds, normalized to",
        f"// the least-filled icon ({target * 100:.1f}% of canvas height) so nothing",
        "// overflows its container.",
        "//",
        "// Unknown ids fall back to 1 — a new Sprite renders unscaled rather than",
        "// wrong, until this is regenerated.",
        "const ICON_SCALE: Record<string, number> = {",
    ]
    for sid, k in sorted(scales.items(), key=lambda kv: kv[1]):
        lines.append(f'  "{sid}": {k},')
    lines += [
        "};",
        "",
        "export function spriteIconScale(spriteId: string): number {",
        "  return ICON_SCALE[spriteId] ?? 1;",
        "}",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"\nwrote {OUT.relative_to(ROOT)} ({len(scales)} sprites)")


if __name__ == "__main__":
    main()
