/** A named map location ("POI"), positioned in the same normalized [0,1] map-fraction space as findings. */
export interface Poi {
  id: string;
  name: string;
  x: number;
  y: number;
}

export interface PoiCatalog {
  source: string;
  generated: string;
  count: number;
  pois: Poi[];
}

/**
 * Loads the island's named locations — generated by
 * scripts/scrape-fortnite-gg-pois.mjs from fortnite.gg's own map data (the
 * same source as our map tiles), so positions line up exactly with no
 * separate conversion step. Static file, same pattern as the Sprite catalog
 * (see lib/sprite-catalog/repository.ts) — no runtime dependency on
 * fortnite.gg.
 */
export async function loadPois(): Promise<PoiCatalog> {
  const res = await fetch("/data/pois.json");
  if (!res.ok) {
    throw new Error(`Failed to load /data/pois.json: ${res.status}`);
  }
  return res.json();
}
